name: Deploy
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - run: npm i -g @railway/cli
      - run: yarn install

      - run: yarn client:build
      - run: yarn server:build
      - run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
